# NumPy (singkatan dari Numerical Python) adalah library Python untuk:

✅ Perhitungan numerik (angka)
✅ Pemrosesan data dalam bentuk array dan matriks
✅ Operasi matematis cepat (tanpa for loop)

# Array
Array di NumPy = kumpulan elemen (angka, bisa juga string) yang:
- Ukurannya tetap
- Tipenya sama (semua int, semua float, dsb)
- Disimpan dalam satu blok memori (jadi cepat dan efisien)


# Perbandingan: List Python vs Array NumPy
| Aspek              | List Python                | Array NumPy                             |
| ------------------ | -------------------------- | --------------------------------------- |
| Tipe data campuran | Bisa campuran (`[1, "a"]`) | Harus 1 tipe data (semua `int`, dsb)    |
| Operasi matematis  | Tidak otomatis             | Bisa langsung (`array * 2`)             |
| Kecepatan          | Lebih lambat               | Lebih cepat (pakai C di belakang layar) |
| Ukuran memori      | Lebih besar                | Lebih kecil                             |


# Kenapa Array Lebih Cepat daripada List?
List di Python adalah struktur data umum yang bisa menyimpan apa saja (string, int, objek, bahkan list lagi) . Tapi karena sifatnya fleksibel, ia tidak efisien untuk operasi numerik besar.

# Sedangkan array NumPy :
Menyimpan satu tipe data saja (misal: int64, float32)
Menyimpan data dalam lokasi memori yang berdekatan → akses lebih cepat
Memungkinkan operasi vektorisasi (tidak perlu loop manual)

In [1]:
# Contoh

# List biasa
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)       # Gabung list, hasilnya: [1, 2, 3, 4, 5, 6]

# NumPy array
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)       # Operasi elemen: [5 7 9]


[1, 2, 3, 4, 5, 6]
[5 7 9]


# Apa Bedanya Array vs Tabel (Seperti di Pandas)?
| Aspek     | NumPy Array                       | Pandas DataFrame (Tabel)               |
| --------- | --------------------------------- | -------------------------------------- |
| Bentuk    | 1D, 2D, nD (array/matriks/tensor) | 2D saja (seperti Excel)                |
| Label     | Tidak ada (akses pakai indeks)    | Ada label (kolom, baris)               |
| Fokus     | Operasi numerik cepat             | Analisis data tabular (label + angka)  |
| Kecepatan | Lebih cepat (karena simpel)       | Sedikit lebih lambat (lebih fleksibel) |

# Contoh Analogi:
Array NumPy = Excel sheet mentah tanpa header, hanya angka.
DataFrame Pandas = Excel sheet lengkap dengan header, bisa campur string, tanggal, dll.


# Kenapa Data Engineer Perlu NumPy?
Walaupun Data Engineer banyak memakai SQL dan Pandas, NumPy penting untuk:
- Melakukan transformasi numerik sebelum loading data
- Optimasi memori saat menangani data besar
- Memahami konsep array yang digunakan juga di Pandas, TensorFlow, PyTorch, Spark

# Istilah di Numpy
| Istilah        | Penjelasan                                                         |
| -------------- | ------------------------------------------------------------------ |
| `ndarray`      | Nama resmi untuk "array" di NumPy                                  |
| `dimensi`      | 1D (list), 2D (matriks), 3D (tensor), dst                          |
| `shape`        | Ukuran array per dimensi, contoh `(3, 4)` artinya 3 baris, 4 kolom |
| `dtype`        | Tipe data array (`int32`, `float64`, dsb)                          |
| `broadcasting` | Cara NumPy menyesuaikan bentuk array saat operasi                  |
| `axis`         | Sumbu array (axis 0 = baris, axis 1 = kolom di array 2D)           |



# Indexing

arr2d = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

# Bayangkan seperti tabel Excel:
      Kolom
       0  1  2
     ---------
B 0 | 1  2  3
a 1 | 4  5  6
r 2 | 7  8  9


In [ ]:
# Indexing 2D (mengambil elemen spesifik)

print(arr2d[1, 2])

# Penjelasan :
# Ambil baris ke-1, kolom ke-2 → hasilnya: 6

6


In [3]:
# Membuat Array 1 Dimensi (1D)

arei = np.array([1,2,3,4,5])
print(arei)

[1 2 3 4 5]


In [13]:
# # Membuat Array 2 Dimensi (2D)

arei = np.array([[1,2,3,4,5], [65120, 65122, 65121, 65123, 65124]])
print(arei)

[[    1     2     3     4     5]
 [65120 65122 65121 65123 65124]]


In [ ]:
# Mengecek Info Array

print(arei.shape) # output 2, 5 maksudnya 2 baris, 5 kolom
print(arei.ndim) # output 2 dimensi
print(type(arei)) # objectnya array
print(arei.dtype) 

# Mengapa dtype hasilnya U21 karena :
    # Menggabungkan angka (int) dan teks (str) dalam 1 array.
    # NumPy tidak bisa campur-campur tipe data dalam 1 array seperti Pandas DataFrame.
    # Karena ada teks (string), maka NumPy otomatis mengubah semua elemen jadi string agar seragam.

#  Apa itu <U21?
    # < = little-endian (urutan byte, abaikan untuk sekarang)
    # U = Unicode string
    # 21 = maksimum panjang karakter adalah 21 karakter (karena "Muhammad" punya 8 huruf, "Rasyid" 6, "Shanks" 6, 
                                    #    dst—jadi NumPy alokasikan memori berdasarkan yang terpanjang + cadangan).



(2, 5)
2
<class 'numpy.ndarray'>
int64


In [9]:
# Jika ingin menggabungkan tipe data yang berbeda gunakan pandas dataframe

import pandas as pd

df = pd.DataFrame({
    "Nomor": [1, 2, 3, 4, 5],
    "Nama": ['Muhammad','Rasyid','Ridho','Kaido','Shanks']
})

print(df.dtypes)


Nomor     int64
Nama     object
dtype: object


In [ ]:
# Slicing (Memotong Bagian Array)

# 1D
arei2 = np.array(['Muhammad','Rasyid','Ridho','Kaido','Shanks'])
print(arei2[1:4])     # dari indeks 1 ke 3, Rasyid, Ridho, Kaido
print(arei2[:3])      # dari awal ke indeks 2 'Muhammad','Rasyid','Ridho'
print(arei2[::2])     # ambil tiap 2 langkah, langkah pertama dari index 0 yaitu Muhammad, 2 langkah ke depan yaitu Ridho


['Rasyid' 'Ridho' 'Kaido']
['Muhammad' 'Rasyid' 'Ridho']
['Muhammad' 'Ridho' 'Shanks']


In [ ]:
# Slicing 2D

arr2d = np.array([[1, 2, 3], # baris ke 0
                  [4, 5, 6], # baris ke 1
                  [7, 8, 9]])# baris ke 2
        # kolom ke 0  1  2

print(arr2d[:2, 1:])

# Artinya

# :2 → ambil baris ke-0 dan ke-1 (stop di baris ke-2, tapi tidak diambil)
# 1: → ambil kolom mulai dari ke-1 sampai akhir

# Output
# [[2 3]
#  [5 6]]

# Ambil 2 baris pertama dan semua kolom
print(arr2d[:2,:])

# : ambil semua baris atau kolom
print(arr2d[:,:])

# ambil nilai tertentu saja misal 5
print(arr2d[1:2,1:2])

# Penjelasan :
    # Posisi angka 5 ada di:
    # Baris ke-1
    # Kolom ke-1

# Maka:
# 1:2 artinya ambil baris ke-1 saja (karena akhir tidak termasuk)
# 1:2 artinya ambil kolom ke-1 saja
# Jadi kita mengambil angka 5, dalam bentuk array 2 dimensi berukuran 1×1.

# ambil nilai tertentu misal 6
print(arr2d[1:2,2:])
# 1:2 artinya ambil baris ke-1 saja (karena akhir tidak termasuk)
# 2: dimulai dari kolom ke 2 dan jika tidak ada kolom setelahnya maka akan dianggap selesai

[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5]]
[[6]]


# Konsep Slicing

arr[baris_start:baris_stop, kolom_start:kolom_stop]

- baris_start → mulai dari baris ke berapa (mulai dari 0)
- baris_stop → berhenti SEBELUM baris ke berapa
- kolom_start, kolom_stop → sama seperti di atas

# Contoh Array 2D

arr2d = np.array([
  [1, 2, 3],   # baris ke-0
  [4, 5, 6],   # baris ke-1
  [7, 8, 9]    # baris ke-2
])

# Kalau dibayangkan bentuknya seperti tabel:
[ [1, 2, 3],   ← baris 0
  [4, 5, 6],   ← baris 1
  [7, 8, 9] ]  ← baris 2
    ↑  ↑  ↑
   kol 0 1  2


# Modul 3 Operation and Broadcasting

In [ ]:

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)  # [11 22 33]

# Penjumlahan dilakukan elemen demi elemen:
    # 10 + 1 = 11
    # 20 + 2 = 22
    # 30 + 3 = 33

# Operasi lain
print(a - b)  # [ 9 18 27]
print(a * b)  # [10 40 90]
print(a / b)  # [10. 10. 10.]


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [ ]:
# Operasi dengan Skalar (1 angka ke semua elemen)

print(a + 5)  # [15 25 35] # 10+5, 20+5, 30+5
print(b * 2)  # [2 4 6]    # 1*2, 2*2, 3*2


[15 25 35]
[2 4 6]


In [ ]:
# Operasi Matrix 2D - Penjumlahan elemen per posisi

x = np.array([[1, 2], [3, 4]])
y = np.array([[10, 20], [30, 40]])
print(x + y)
print(x - y)
print(x * y)

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]


In [ ]:
# Agregasi

print(np.sum(a))     # Total semua elemen: 60
print(np.mean(a))    # Rata-rata: 20.0
print(np.min(a))     # Minimum: 10
print(np.max(a))     # Maksimum: 30
print(np.median(a)) 

60
20.0
10
30
20.0


In [ ]:
#  Agregasi Matrix

z = np.array([[1, 2, 3],
              [4, 5, 6]])
print(z)

# Jumlah semua nilai pada array
print(np.sum(z))  # 21

# jumlah nilai pada tiap baris
print(np.sum(z, axis=1))  # [6 15]
# 6 baris ke 0
# 15 baris ke 1

# Jumlah per kolom:
print(np.sum(z, axis=0))  # [5 7 9]
# Kolom 0 → 1+4 = 5
# Kolom 1 → 2+5 = 7
# Kolom 2 → 3+6 = 9

[[1 2 3]
 [4 5 6]]
21
[ 6 15]
[5 7 9]


In [ ]:
#  Boolean Operation (Perbandingan)

print(a > 15)  # [False  True  True]

# Penjelasan :
# Apakah 10 > 15? ❌
# Apakah 20 > 15? ✅
# Apakah 30 > 15? ✅

[False  True  True]


In [ ]:
# Filtering pakai Boolean

print(a[a > 15])  # [20 30]

# artinya, ambil nilai array a yang lebih dari 15


In [ ]:
# Broadcasting 2D vs 1D

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)

# Penjelasan:
    # Baris [10 20 30] diulang ke tiap baris matrix A
    # Ini namanya broadcasting baris

[[11 22 33]
 [14 25 36]]


# Modul 4: Reshape dan Manipulasi Bentuk Array
🎯 Tujuan Modul:
Mengubah bentuk array (misalnya dari 1D ke 2D, atau 3x3 ke 9x1)

Ini penting saat kamu mau menyesuaikan data sebelum diproses atau dikirim ke pipeline/machine learning model

🧠 Kenapa perlu belajar reshape?
Bayangkan kamu punya array 9 elemen, tapi model butuh input bentuk 3x3. Maka kamu perlu mengubah bentuknya, bukan nilainya.

# Fungsi-fungsi penting di Modul ini:
| Fungsi        | Kegunaan Singkat                                    |
| ------------- | --------------------------------------------------- |
| `reshape()`   | Ubah bentuk array                                   |
| `flatten()`   | Jadikan array 2D menjadi 1D (salinan)               |
| `ravel()`     | Sama seperti `flatten`, tapi **lebih hemat memori** |
| `transpose()` | Menukar baris ↔ kolom                               |
| `T`           | Shortcut untuk `transpose()`                        |


In [ ]:
# Reshape: Ubah bentuk array

arr = np.arange(9)  # array dari 0 sampai 8 (total 9 elemen)
print(arr)          # [0 1 2 3 4 5 6 7 8]

arr2d = arr.reshape(3, 3)
print(arr2d)

# Catatan:
    # reshape(baris, kolom) → total elemennya harus cocok
    # 9 elemen → reshape(3, 3) ✅
    # 9 elemen → reshape(2, 4) ❌ (karena butuh 8 elemen)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Flatten dan Ravel: dari 2D ke 1D

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

flat = arr2d.flatten()
rav = arr2d.ravel()

print(flat)  # [1 2 3 4 5 6]
print(rav)   # [1 2 3 4 5 6]

# Perbedaannya:
# | Fungsi      | Salinan baru? | Bisa hemat memori? |
# | ----------- | ------------- | ------------------ |
# | `flatten()` | Ya            | Tidak              |
# | `ravel()`   | Tidak (view)  | Ya (lebih efisien) |

# Biasanya ravel() cukup untuk data engineer saat ingin transformasi ringan.



[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# Transpose / T: Tukar baris dan kolom

arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print(arr.shape)     # (3, 2)

# Ada 3 baris:
# 👉 [[1, 2], [3, 4], [5, 6]]
# → masing-masing daftar adalah 1 baris

# Setiap baris punya 2 kolom:
# 👉 [1, 2] → 2 angka

# Catatan
    # sebelum transpose tidak harus pakai .shape dulu karena keduanya bisa langsung dipakai secara terpisah.
    # Fungsi .shape hanya digunakan untuk melihat bentuk array.
    # Sedangkan .T atau .transpose() digunakan untuk mengubah bentuknya.

transpose = arr.T
print(transpose)
print(transpose.shape) # cek perubahan baris dan kolom, sekarang berubah menjadi 2 baris 3 kolom

# [[1 3 5]
#  [2 4 6]]

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [ ]:
# reshape (-1, n)
arr2d = np.arange(12)  # 0 sampai 11
print(arr2d)

print(arr.reshape(-1, 3))  # 4 baris, 3 kolom otomatis
print(arr.reshape(3, -1))  # 3 baris, 4 kolom otomatis


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Penjelasan Reshape
Analogi
"Saya ingin ubah bentuk array ini jadi punya n kolom, tolong NumPy hitung otomatis berapa baris yang cocok."
📌 -1 = “biarkan NumPy yang hitung”
📌 n = jumlah kolom yang kamu tetapkan

# Aturan Penting .reshape():
Total elemen harus habis dibagi (tanpa sisa) oleh baris × kolom.

In [55]:
# contoh
arr1 = np.arange(12)  # [0, 1, 2, ..., 11]
print(arr1)

print(arr1.reshape(-1, 3)) # 12 total elemen, kamu mau 3 kolom → berarti butuh 4 baris

arr2 = np.arange(12)
print(arr2.reshape(3,-1)) # Saya mau bentuk array ini jadi 3 baris. NumPy tolong hitung sendiri berapa kolom


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Fancy Indexing dan Boolean Masking

Fancy Indexing = Ambil data berdasarkan nomor/posisi tertentu yang kamu tentukan
Analogi sederhana:
    - Bayangkan kamu punya sekantong permen dengan berbagai rasa. Kamu ingin memisahkan hanya permen rasa strawberry. Boolean masking seperti punya "saringan ajaib" yang hanya meloloskan permen dengan kriteria tertentu.

Boolean Masking = Saring data berdasarkan kondisi tertentu (seperti filter)
Analogi sederhana :
    Bayangkan kamu punya sekantong permen dengan berbagai rasa. Kamu ingin memisahkan hanya permen rasa strawberry. Boolean masking seperti punya "saringan ajaib" yang hanya meloloskan permen dengan kriteria tertentu.

In [ ]:
# Fancy Indexing

# Ini seperti deretan loker dengan isinya
loker = np.array([10, 20, 30, 40, 50, 60])
print("Isi semua loker:", loker)

# Fancy indexing: ambil barang dari loker nomor 1, 3, dan 5 sekaligus
nomor_loker = [1, 3, 5]
    # Kita membuat sebuah list Python biasa berisi angka [1, 3, 5]
    # Angka-angka ini adalah nomor index yang ingin kita ambil dari array loker
    # Kita ingin mengambil data dari posisi tertentu, bukan semua data
    # Angka 1, 3, 5 adalah alamat/posisi dalam array yang ingin kita akses


barang_yang_diambil = loker[nomor_loker]
# loker[nomor_loker] artinya: "ambil nilai dari array loker pada posisi-posisi yang ada di nomor_loker"
# NumPy secara otomatis akan:
    # Baca nomor_loker[0] = 1 → ambil loker[1] = 20
    # Baca nomor_loker[1] = 3 → ambil loker[3] = 40
    # Baca nomor_loker[2] = 5 → ambil loker[5] = 60
# Hasilnya disimpan dalam variabel barang_yang_diambil

print("Barang dari loker 1, 3, 5:", barang_yang_diambil)  # [20, 40, 60]

# Kegunaan praktis: Misalnya kamu punya daftar nilai siswa dan ingin mengambil nilai siswa tertentu berdasarkan nomor absen mereka.

Isi semua loker: [10 20 30 40 50 60]
Barang dari loker 1, 3, 5: [20 40 60]


In [ ]:
# Boolean Masking

# Ini seperti sekantong permen dengan nilai manisnya
permen = np.array([5, 8, 2, 9, 6, 3, 7])
print("Tingkat manis semua permen:", permen)

# Boolean masking: cari permen yang manisnya > 6
saringan = permen > 6  # Ini menghasilkan True/False untuk setiap permen
# NumPy membandingkan setiap elemen dalam array permen dengan angka 6
# Proses yang terjadi di belakang layar:
    # permen[0] = 5 → 5 > 6? → False
    # permen[1] = 8 → 8 > 6? → True
    # permen[2] = 2 → 2 > 6? → False
    # permen[3] = 9 → 9 > 6? → True
    # permen[4] = 6 → 6 > 6? → False
    # permen[5] = 3 → 3 > 6? → False
    # permen[6] = 7 → 7 > 6? → True
# Hasilnya adalah array Boolean: [False, True, False, True, False, False, True]
print("Saringan (True/False):", saringan)  # [False, True, False, True, False, False, True]

# Mengapa seperti ini:
    # Kita ingin membuat "peta" atau "cetakan" yang menunjukkan mana saja elemen yang memenuhi syarat
    # Operator > di NumPy secara otomatis diterapkan ke semua elemen (disebut vectorized operation)
    # Hasilnya berupa array True/False yang ukurannya sama dengan array asli

# Ambil hanya permen yang lolos saringan
permen_manis = permen[saringan]
print("Permen yang sangat manis:", permen_manis)  # [8, 9, 7]

Tingkat manis semua permen: [5 8 2 9 6 3 7]
Saringan (True/False): [False  True False  True False False  True]
Permen yang sangat manis: [8 9 7]
